### ISSUE TITLE
Confilct problem

### ISSUE THREAD

**Issue by IngAmanda** [Dinknesh/Traffic#12]
Guys, i can't pull the modification of Jhana (login and register branch). I make some changes on my side. I rename some files, create package. I'm working on the issue but i need some help. please

**Comment by JHANAGUSTAVE** [comment]
what you will do is create another branch, pull the files, and make the changes you have to make. want it not to change too

**Comment by IngAmanda** [comment]
ok

**Comment by KeitelDOG** [comment]
When you push a branch, you have to merge it with the master branch with a pull request. Only after that the branch codes will be available in master. You don't need to pull the branch that your collaborators pushed, except if you want to correct it before you pushes it again and merges it.
